vcluster:
  controlPlane:
    ingress:
      enabled: true
      # Host is the host where vCluster will be reachable
      host: vcluster.172.21.0.2.nip.io
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      spec:
        ingressClassName: nginx-external
        tls:
          - hosts:
              - vcluster.172.21.0.2.nip.io
  exportKubeConfig:
    context: vcluster
    server: vcluster.172.21.0.2.nip.io
    secret:
      name: vcluster-kubeconfig
